---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo 'init script' # runs during prebuild
    command: |
      echo 'start script'
image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - ritwickdey.LiveServer